version: '3'
services:
  php-apache:
    container_name: php-apache
    image: tomsik68/xampp:7
    volumes:
     - ./php:/www
    ports:
     - 8000:80
    depends_on:
      - db
  db:
    container_name: mysql
    image: mysql:5.7.40
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"